# Generated by Django 4.2.7 on 2023-11-14 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('logo', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchday', models.IntegerField()),
                ('utcDate', models.DateTimeField()),
                ('status', models.CharField(max_length=30)),
                ('score_home', models.PositiveIntegerField(default=0)),
                ('score_away', models.PositiveIntegerField(default=0)),
                ('awayTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='apiapp.team')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.competition')),
                ('homeTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='apiapp.team')),
            ],
        ),
    ]
