# Generated by Django 4.2.7 on 2023-11-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='competitions',
            field=models.ManyToManyField(to='apiapp.competition'),
        ),
    ]
