# Generated by Django 4.2.7 on 2023-11-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_rename_status_schedule_match_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='score_away',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='score_home',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
